language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.3
    - android-30
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - android-sdk-preview-license.+
    - android-sdk-license.+
    - google-gdk-license-+
    - intel-android-extra-license.+
    - android-sdk-arm-dbt-license.+
jdk:
  - oraclejdk8
script:
  - "./gradlew assembleRelease --stacktrace"
before_install:
  - yes | sdkmanager "platforms;android-30"
env:
  global:
    secure: fC4rDkt8qxZaTz+ebDZyjLLK3BGkiG/Pe46t7TFmd8MIojbEPTG/HX0EhU8m2NkNRYTVJDYzM5eYs5TQfveyO2EHNJ5PFdHQ8tDSAIrY9H+lmPFtrwac7oaGMWdSRJgPf4kjEHV5MYzc6+rgBZVriL13pc6+o3PNSTe8/dP7Nup29sNbH7e9H1jdcrHHuqV+277WrI2qBA6RvgZO6rctj9KYxz1oO58NjYzHOPaNh2kYUZhikgBiqCr4qgupU99cZ6PG8vgHcWNrh64V8MBB75tpcQ1Ry8Mz3UPlP3iKrOvMP0OO7XIcqPaKGCQwNIObiXctXVaL2hUgKqcDUegMPKZfiP6jzno8/uKW3PvvraCjSPSmfIucfBpZ4n8PwNgQlsHTAgYIY1VpZ4VTQ/Ywbrj420YK1DrIQisvCNVT6BKpWdbJaNpwCO53dJunPchyExOApQ79XwxMuzVrheH4FlCKnyiVbde0t11jFaHLvVIktqL/hVr82y7ixMurGRGFTJUIvoZIqcdl0xZrnYLLWILTCywRSW3YIYtGUGAo8hhEi85RvOZGuoQ12gsfy97Ga3vS6UK2502WripuPlq9Uzhb70iAD0cLhXTB3EP7Sx2okxHbtez0dzl8ZUyqlIh8LXYSDM5Ws89WOJIYQ3Zs+lfsQQlTTkYdADr8u42GQI4=
deploy:
  provider: releases
  skip_cleanup: 'true'
  api_key: "${GH_TOKEN}"
  file: app/build/outputs/apk/release/app-release.apk
  on:
    tags: true
